### ISSUE TITLE
Error on require

### ISSUE THREAD

**Issue by arthurtofani** [kyoungmo-yang/irtruby#1]
Hello,
I followed all the steps on documentation and got my Makefile. After 'make' (without parameters, because I didn't see none at documentation), I tried to run in console:

irb(main):002:0> require './irt'

and got it

LoadError: /home/arthur/irtruby/lib/irt_ruby.so: undefined symbol: Init_irt_ruby - /home/arthur/irtruby/lib/irt_ruby.so

the generated .so file is in the right place and looks like OK... any ideas?

I'ḿ using Ubuntu 13.10 and Ruby 1.9.3

**Comment by Celumproject** [comment]
@arthurtofani Did you find a solution?

**Comment by kyoungmo-yang** [comment]
Sorry, I omitted a step. 
IRT_RUBY is required SWIG(http://www.swig.org/).
If you are using Ubuntu, run commands as follows:
$> sudo apt-get install swig
$> make clean && make

You can see full steps in README.

**Comment by kyoungmo-yang** [comment]
Sorry, I omitted a step. 
IRT_RUBY is required SWIG(http://www.swig.org/).
If you are using Ubuntu, run commands as follows:
$> sudo apt-get install swig
$> make clean && make

You can see full steps in README.
